language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update
  - sudo aptitude install libfltk1.3 libfltk1.3-dev libboost1.48-dev libgsl0-dev
script:
  - mkdir build
  - cd build
  - cmake ..
make -j8
branches:
  only:
    - master
os:
  - linux
