language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install libxmu-dev libxi-dev freeglut3-dev libfltk1.3 libfltk1.3-dev libboost1.48-dev libgsl0-dev
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
branches:
  only:
    - master
os:
  - linux
